# Should the plugin prevent beds from being slept in?
prevent-bed-usage: true

# Should the plugin prevent users from adjusting their
# respawn point using beds?
prevent-respawn-set: false

# This section allows the configuration of an
# error message sent to the user if 'prevent-bed-usage'
# is enabled.
message:

  # Should the message be sent?
  send: true

  # What should the message be?
  text: '&b&lBedDefender: &7Sleeping in beds is disabled on this server.'