name: 'BedDefender'
version: '${project.version}'
main: 'me.lokka30.beddefender.BedDefender'
description: '${project.description}'
authors: ['lokka30']
api-version: '1.13'
website: 'https://github.com/lokka30/BedDefender'